name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos:
    name: macos
    runs-on: macos-latest
    strategy:
      matrix:
        feature:
          - default
          - blocking-wrappers
          - ""
        rust:
          - stable
          - beta
          - stable minus 5 releases
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: check (features "${{matrix.feature}}")
        run: cargo check --no-default-features --features "${{matrix.feature}}"

      - name: test (features "${{matrix.feature}}")
        run: cargo test --no-run --features "${{matrix.feature}}"

      - name: clippy (features "${{matrix.feature}}")
        run: cargo clippy -- -D warnings
