name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos:
    name: macos
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - stable minus 5 releases
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: check (default features)
        run: cargo check

      - name: test (default features)
        run: cargo test --no-run

      - name: clippy (default features)
        run: cargo clippy -- -D warnings
